### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by davidbrochart** [samuelcolvin/watchfiles#116]
Just to let you know that watchfiles is now available on conda-forge. It can be installed using `mamba` or `conda`:
```python
mamba install -c conda-forge watchfiles
```
Let me know if you want to be part of the package maintainers, and I'll add you to the list.

**Comment by samuelcolvin** [comment]
Thanks so much, probably best, yes please.

Also happy to accept a pr to add this to the docs.

**Comment by davidbrochart** [comment]
> Also happy to accept a pr to add this to the docs.

See #117.
