### ISSUE TITLE
Do timeouts work on windows?

### ISSUE THREAD

**Issue by hucker** [samuelcolvin/watchfiles#137]
The filtering and notifications all work great but I can't make a timeout happen based on changing the rust_timeout and the yield_on_timeout.  I have tried many variations.  I am testing on windows.

```
for changes in watchfiles.watch('.', watch_filter=dpcs_filter, rust_timeout=1000, yield_on_timeout=True, debug=False):
        print(changes)
```

**Comment by samuelcolvin** [comment]
Yes they should work. The only thing that I think won't work is signals - e.g. cancelling the  watcher in the middle of a step using ctrl+c.

If they really don't, I'll need more details to investigate.

**Comment by samuelcolvin** [comment]
Have you tried `yield_on_timeout` to actually see the timeouts?

**Comment by hucker** [comment]
Never mind.   I found my mistake.  I setup a loop to iterate over the changes sequence thinking the changes object would tell me about the timeout.  I didn't realize that a timeout returns an empty change list so my inner loop wasn't entered.


``` python
    for changes in watchfiles.watch('.', rust_timeout=1000, yield_on_timeout=True, debug=True):
        for change, path in changes:
            if change == watchfiles.Change.added or change == watchfiles.Change.modified :
                print(f"{change=}, {path=}")
```
