### ISSUE TITLE
Can't install on alpine

### ISSUE THREAD

**Issue by bbasics** [samuelcolvin/watchfiles#142]
On `python:3.8.0-alpine` I tried to install but:

```
running build_rust
error: failed to parse manifest at "/usr/src/app/watchfiles/watchfiles/Cargo.toml"

Caused by:
  failed to parse the `edition` key

Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown
```

What happen, and how to fix it?
Thanks :)

**Comment by samuelcolvin** [comment]
What happened: there was no suitable binary, so pip tried to install from source, rust was installed but the version was too old.

Hopefully the binary problem is fixed by #131, could you try installing the wheel from recent main CI files to confirm?

Otherwise the solution is to install latest (stable) rust before trying to install watchfiles.

**Comment by samuelcolvin** [comment]
Any particular reason you're using `python:3.8.0-alpine`? 3.8.0 is pretty old now - that might be why you have an old version of rust.

I've just tried this with:

```bash
docker run -it python:3.8-alpine apk add bash
docker ps -a
# find the id of the container we just created
docker commit <new-container-id> python:3.8-alpine-with-bash
docker run -it --rm python:3.8-alpine-with-bash bash
> apk update
> apk add rust cargo
> pip install watchfiles
```

And it works fine. Obviously you could do the same in a Dockerfile without the need to install bash etc.

---

I also tried installing the binaries from `main` and they're working well

```bash
docker run -it --rm -v /home/samuel/Downloads/watchfiles_pypi_files:/watchfiles_pypi_files python:3.8-alpine-with-bash bash
> ls /watchfiles_pypi_files
> pip install /watchfiles_pypi_files/watchfiles-0.0.dev0-cp38-cp38-musllinux_1_1_x86_64.wh
> # watch the same directory since it's mounted so we can make changes from the host
> watchfiles "python -c 'import os;print(os.getenv(\"WATCHFILES_CHANGES\"))'" /watchfiles_pypi_files/
> ... changes printed
```

So until the next version is released, you can use files download from [CI](https://github.com/samuelcolvin/watchfiles/actions/runs/2319175400) (see "pypi_files").

Closing this as it's fixed on main.

**Comment by bbasics** [comment]
Thanks for the very quick answer!
It seems to work now indeed, I don't understand, something has changed?

**Comment by samuelcolvin** [comment]
Yes, I released the new version.
