### ISSUE TITLE
Notify's PollWatcher with_delay removed

### ISSUE THREAD

**Issue by davidbrochart** [samuelcolvin/watchfiles#144]
### Description

The [conda package](https://github.com/conda-forge/watchfiles-feedstock/pull/5) fails to compile `watchfiles` v0.14 because if downloads `notify` v5.0.0-pre.15. I'm not sure why since it is v5.0.0-pre.14 in [Cargo.toml](https://github.com/samuelcolvin/watchfiles/blob/a5b59fa51cbcfb6242794bba704657c4ad760988/Cargo.toml#L8).
And `with_delay` [has been removed](https://github.com/notify-rs/notify/commit/f3c38f128808fa5ccd05e1641cc67f3ba502f448) in `notify` v5.0.0-pre.15.

### Operating System

Ubuntu 22.04

### Watchfiles Version

v0.14

### Python Version

3.10

**Comment by samuelcolvin** [comment]
Fun, and weird.

Should be easy enough to remove it.

**Comment by samuelcolvin** [comment]
Is it worth asking the conda people why the wrong rust package was downloaded?

**Comment by davidbrochart** [comment]
It's because [of this](https://doc.rust-lang.org/cargo/reference/resolver.html#pre-releases):

Cargo allows "newer" pre-releases to be used automatically. For example, if 1.0.0-beta is published, then a requirement foo = "1.0.0-alpha" will allow updating to the beta version.

**Comment by samuelcolvin** [comment]
😞 I really don't understand why notify is versioned the way it is.

I'll fix this and create an issue asking for a proper release ok notify.

**Comment by samuelcolvin** [comment]
should be fixed by #146, once that's merged we can release a patch version.
