### ISSUE TITLE
Feature Request- ability to specify timeout when using CLI

### ISSUE THREAD

**Issue by tedivm** [samuelcolvin/watchfiles#152]
I love this project and am using it the [Multi-Py Celery project](https://github.com/multi-py/python-celery).

One problem I ran into though is that Celery can take longer than the 5 seconds (which appears to be [hardcoded here](https://github.com/samuelcolvin/watchfiles/blob/d83f822648d72fb3a18be4980adf0f2f0d750239/watchfiles/run.py#L286)). Exposing the timeout- either via a CLI arg or envvar- would be super appreciated.

Thanks!

**Comment by samuelcolvin** [comment]
Thanks, PR welcome to make it configurable.
