### ISSUE TITLE
Takes time to interrupt/stop both awatch and arun_process

### ISSUE THREAD

**Issue by martolini** [samuelcolvin/watchfiles#162]
### Description

This might also be a question;

When ran with `anyio`, it seems like it takes a couple seconds to be interrupted. Is this by design, and/or is this something that can be tweaked?

Thanks!

### Example Code

```Python
from watchfiles import awatch

async for change in awatch('.'):
  pass
```

### Example Code Output

```Text
When trying to interrupt this, it hangs for ~0-5 seconds
```

### Operating System

Mac & Windows

### Watchfiles Version

0.14.1

### Python Version

3.9.10

**Comment by samuelcolvin** [comment]
I think this is a result of #136, you can probably change the delay with `rust_timeout`.

**Comment by samuelcolvin** [comment]
Are you sure this is slow with macos? I would expect it with Windows, but not macos.

**Comment by samuelcolvin** [comment]
Are you interrupting with just Ctrl+C?

**Comment by samuelcolvin** [comment]
Does adjusting `rust_timeout` make a difference?

Sorry, on my phone waiting for a flight, so can't test.

**Comment by samuelcolvin** [comment]
Your code doesn't run, but I've tried the following on MacOS and it exits immediately

```py
import anyio
from watchfiles import awatch


async def main():
  async for change in awatch('.'):
    print(change)


if __name__ == '__main__':
    anyio.run(main)
```

**Comment by samuelcolvin** [comment]
I'll need a working demo of the problem to look into it further.
