### ISSUE TITLE
Errors on `WSL` and docker with windows

### ISSUE THREAD

**Issue by austinorr** [samuelcolvin/watchfiles#169]
### Description

`watchfiles` appears to be fully pip installable for windows, but I can't seem to get a minimal example working on Linux. The below MRE is straight from the docs and works great on windows. That is, when I change the foobar.py file the simple server is relaunched. 

However if I try the same MRE on via wsl (ubuntu) or docker (debian) I don't see any change events firing. This was discovered while updating `uvicorn` 0.17x->0.18x in which they transitioned to this package for --reload file-watching rather than `watchgod`.

The following MRE was tested in new conda environments on both windows (it worked well) and Ubuntu (it didn't detect changes).

---
_foobar.py_
```python
import os, json
from aiohttp import web

async def handle(request):
    # get the most recent file changes and return them
    changes = os.getenv("WATCHFILES_CHANGES")
    changes = json.loads(changes)
    return web.json_response(dict(changes=changes))


app = web.Application()
app.router.add_get("/", handle)


def main():
    web.run_app(app, port=8000)

```
---
_requirements.txt_
```shell
aiohttp
watchfiles==0.15.0

```
---
_shell_
```shell
$watchfiles foobar.main
[17:05:44] watchfiles 👀  path="$HOME$/sources/watchfiles-bug" target="foobar.main" (function) filter=DefaultFilter...
======== Running on http://0.0.0.0:8000 ========
(Press CTRL+C to quit)
```

On Linux, this output is never updated when `foobar.py` changes, but on windows the expected notifications of the changes occur and the module reloads correctly. 

Is this expected? Are there other dependencies on Linux that need to be installed for the binaries to work, e.g., do I need to install rust?

It's entirely likely that this is a me-issue, but if this is verified to be an issue for others I wonder if it's possible to catch this sort of thing in the ci action with a build step that pip installs the built package from pypi on a clean environment (one without the rust compiler) and then runs `watchfiles` with a simple example like this on from the docs. 
The tough part (to me) seems like it'd be making the change and detecting that it was correctly caught by `watchfiles`, but I'd be happy to brainstorm how to handle that if this issue ends up even needing a correction.

### Example Code

```Python
-- see description
```

### Example Code Output

```Text
-- see description
```

### Operating System

linux

### Environment

docker (debian), WSL (ubuntu)

### Watchfiles Version

0.15.0

### Python Version

3.9.13

### Rust & Cargo Version

--

**Comment by samuelcolvin** [comment]
Watchfiles definitely time fine on Linux:
1. If it didn't, we would have heard about it
2. The unit tests are fun on Linux
3. I have a Unix desktop and it runs fine

I think the problem is either in uvicorn or before you're running it on WSL or docker on Windows (I assume).

Can you try the watchfiles example directly?

**Comment by austinorr** [comment]
I agree, I hope this is a me-thing but I've worked hard to carve out all my own code and isolate environment, and I'm still seeing the issue. I think I am trying the watchfiles example directly, the MRE above was run in clean conda environments with only the `aiohttp` & `watchfiles` dependencies (there's no `uvicorn` in the MRE above).

The box I'm on is a windows machine, so my linux is all either wsl or docker via wsl, maybe that's the issue. Or it could be my editor... I'm on VS Code. I'll try looking for an atomic writes option and disabling it.

**Comment by austinorr** [comment]
ok tried it with `force_polling=True` and got this:
```$(base) $ conda activate watchfiles
(watchfiles) $ python watch.py
{(<Change.modified: 2>, './foobar.py')}
{(<Change.modified: 2>, './foobar.py')}
{(<Change.modified: 2>, '.'), (<Change.added: 1>, './foobar.py.069998f79d7903e9db70d14bd8eeaebd.tmp')}
{(<Change.modified: 2>, './foobar.py'), (<Change.deleted: 3>, './foobar.py.069998f79d7903e9db70d14bd8eeaebd.tmp'), (<Change.modified: 2>, '.')}
{(<Change.modified: 2>, '.'), (<Change.added: 1>, './foobar.py.069998f79d7903e9db70d14bd8eeaebd.tmp')}
Traceback (most recent call last):
  File ".../watch.py", line 3, in <module>
    for changes in watch(".", force_polling=True):
  File ".../miniconda3/envs/watchfiles/lib/python3.9/site-packages/watchfiles/main.py", line 105, in watch
    raw_changes = watcher.watch(debounce, step, rust_timeout, stop_event)
_rust_notify.WatchfilesRustInternalError: error in underlying watcher: IO error for operation on ./foobar.py.069998f79d7903e9db70d14bd8eeaebd.tmp: No such file or directory (os error 2) about ["./foobar.py.069998f79d7903e9db70d14bd8eeaebd.tmp"]
```

It works for a while, but eventually it errors due to an apparent read/write issue with that temp file. Based on this, I think it's a WSL thing where the change don't trigger the full chain of events that `notify` expects, so I suppose this is a me-thing after all.

I did try this with `force_polling=False` and I get the same issue-> no changes get fired. It looks like VS Code + WSL doesn't recognize file changes in a compatible way, even with polling.

Since I also have this problem with my docker-based development environment, I wonder if it's related to the fact that these files are 'mounted' into the containers during development causing change events to be bypassed.

**Comment by austinorr** [comment]
Also, I tried editing the file using NotePad (i.e., without VS Code) and had the same issue during the polling=False test (no change events were fired). When polling was True, the notepad edit didn't fail during the 3-5 changes I tried, and likely never would have failed in the same way.

**Comment by austinorr** [comment]
zoiks. Tried something new and it works like a charm. 

This will cause changes to **not** be properly watched for `watchfiles` running on WSL:
1. Launch VS Code from windows-side, e.g., via the context menu.
2. open a WSL terminal window in VS Code 
3. run `watchfiles`
4. be confused....

This works:
1. launch VS Code instance _from WSL_, e.g., via a WSL terminal and the `$code .` command
2. open WSL terminal in WSL
3. run `watchfiles`
4. profit

Today I learned that VS Code on windows != VS Code on WSL. The versions of `uvicorn` < 18 allowed the (anti-)pattern above (windows-side VS Code + WSL terminal) to work just fine, but I can adapt! 

Sorry for wasting your time, and thank you for the patient assistance.

**Comment by samuelcolvin** [comment]
v0.16.0 has just be released with respects the `WATCHFILES_FORCE_POLLING` env. variable allowing you to force polling even when using watchfiles within uvicorn.

**Comment by austinorr** [comment]
Whoa, are you clairvoyant?

https://github.com/encode/uvicorn/pull/1580

**Comment by samuelcolvin** [comment]
:eyes: :partying_face:

**Comment by samuelcolvin** [comment]
Any volunteers for https://github.com/samuelcolvin/watchfiles/issues/187?

**Comment by filwaline** [comment]
There is another bug, I think it is related, and very confusing. 

When run debug-server in docker(WSL2 backend), and the reload_dirs set as `["/"]`, watchfiles won't work.

This can easily reproduce by following code:
```
from watchfiles import watch

for changes in watch('/', force_polling=True):
    print(changes)
```
Files changed, and it keep handling there.

This became a problem, and thanks to [this lines](https://github.com/encode/uvicorn/blob/master/uvicorn/supervisors/watchfilesreload.py#L68-L72), any input of `reload_dirs` will turns into `["/"]`, so watchfiles will never works.

I got no ideas why this happened, any thoughts?

**Comment by HuzaifahLutaaya** [comment]
On a mac M1, am getting this error ;

```
              | Traceback (most recent call last):
api-1               |   File "/opt/pysetup/.venv/bin/uvicorn", line 8, in <module>
api-1               |     sys.exit(main())
api-1               |              ^^^^^^
api-1               |   File "/opt/pysetup/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
api-1               |     return self.main(*args, **kwargs)
api-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1               |   File "/opt/pysetup/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
api-1               |     rv = self.invoke(ctx)
api-1               |          ^^^^^^^^^^^^^^^^
api-1               |   File "/opt/pysetup/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
api-1               |     return ctx.invoke(self.callback, **ctx.params)
api-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1               |   File "/opt/pysetup/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
api-1               |     return __callback(*args, **kwargs)
api-1               |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1               |   File "/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
api-1               |     run(
api-1               |   File "/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 573, in run
api-1               |     ChangeReload(config, target=server.run, sockets=[sock]).run()
api-1               |   File "/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/supervisors/basereload.py", line 50, in run
api-1               |     for changes in self:
api-1               |   File "/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/supervisors/basereload.py", line 69, in __next__
api-1               |     return self.should_restart()
api-1               |            ^^^^^^^^^^^^^^^^^^^^^
api-1               |   File "/opt/pysetup/.venv/lib/python3.11/site-packages/uvicorn/supervisors/watchfilesreload.py", line 87, in should_restart
api-1               |     changes = next(self.watcher)
api-1               |               ^^^^^^^^^^^^^^^^^^
api-1               |   File "/opt/pysetup/.venv/lib/python3.11/site-packages/watchfiles/main.py", line 121, in watch
api-1               |     raw_changes = watcher.watch(debounce, step, rust_timeout, stop_event)
api-1               |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-1               | _rust_notify.WatchfilesRustInter
```


Am wondering why ? Kinda looks similar

**Comment by animemoeus** [comment]
I just got the same problem 🫤

![image](https://github.com/user-attachments/assets/d6dcc03c-2e34-4e38-8c0e-75639ffb409d)

OS: Win 11 (Ubuntu 22 WSL)
Docker Version: Docker Desktop 4.33.1 (161083)

```text
2024-09-01 03:16:29 PostgreSQL is available
2024-09-01 03:16:29 [20:16:29] watchfiles v0.22.0 👀  path="/app" target="celery.__main__.main" (function) filter=PythonFilter...
2024-09-01 03:16:30 celery beat v5.4.0 (opalescent) is starting.
2024-09-01 03:16:32 __    -    ... __   -        _
2024-09-01 03:16:32 LocalTime -> 2024-09-01 03:16:32
2024-09-01 03:16:32 Configuration ->
2024-09-01 03:16:32     . broker -> redis://redis:6379/0
2024-09-01 03:16:32     . loader -> celery.loaders.app.AppLoader
2024-09-01 03:16:32     . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
2024-09-01 03:16:32 
2024-09-01 03:16:32     . logfile -> [stderr]@%INFO
2024-09-01 03:16:32     . maxinterval -> 5.00 seconds (5s)
2024-09-01 03:16:32 [2024-09-01 03:16:32,541: INFO/SpawnProcess-1] beat: Starting...
2024-09-01 03:16:34 Traceback (most recent call last):
2024-09-01 03:16:34   File "/usr/local/bin/watchfiles", line 8, in <module>
2024-09-01 03:16:34     sys.exit(cli())
2024-09-01 03:16:34              ^^^^^
2024-09-01 03:16:34   File "/usr/local/lib/python3.11/site-packages/watchfiles/cli.py", line 171, in cli
2024-09-01 03:16:34     run_process(
2024-09-01 03:16:34   File "/usr/local/lib/python3.11/site-packages/watchfiles/run.py", line 138, in run_process
2024-09-01 03:16:34     for changes in watch(
2024-09-01 03:16:34   File "/usr/local/lib/python3.11/site-packages/watchfiles/main.py", line 121, in watch
2024-09-01 03:16:34     raw_changes = watcher.watch(debounce, step, rust_timeout, stop_event)
2024-09-01 03:16:34                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

---

The weird thing is, I tried running the same repo with Google IDX, and it worked fine

**Comment by animemoeus** [comment]
> I just got the same problem 🫤
> 
> ![image](https://private-user-images.githubusercontent.com/33395829/363439181-d6dcc03c-2e34-4e38-8c0e-75639ffb409d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMzYxMDksIm5iZiI6MTcyNTEzNTgwOSwicGF0aCI6Ii8zMzM5NTgyOS8zNjM0MzkxODEtZDZkY2MwM2MtMmUzNC00ZTM4LThjMGUtNzU2MzlmZmI0MDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDIwMjMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkNDEyOTRmNDIzMjI2OTc1ZTUzOTRiYTc5MzMyYTE0ZjU3OWYzMTZkN2I5MTgwNmFkODdhMmM5ZDg4NDYwNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.P0ONaoPhxYBi74k7tl_ivz7HYHP_NNqGlirlu_LDYQw)
> 
> OS: Win 11 (Ubuntu 22 WSL) Docker Version: Docker Desktop 4.33.1 (161083)
> 
> ```
> 2024-09-01 03:16:29 PostgreSQL is available
> 2024-09-01 03:16:29 [20:16:29] watchfiles v0.22.0 👀  path="/app" target="celery.__main__.main" (function) filter=PythonFilter...
> 2024-09-01 03:16:30 celery beat v5.4.0 (opalescent) is starting.
> 2024-09-01 03:16:32 __    -    ... __   -        _
> 2024-09-01 03:16:32 LocalTime -> 2024-09-01 03:16:32
> 2024-09-01 03:16:32 Configuration ->
> 2024-09-01 03:16:32     . broker -> redis://redis:6379/0
> 2024-09-01 03:16:32     . loader -> celery.loaders.app.AppLoader
> 2024-09-01 03:16:32     . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
> 2024-09-01 03:16:32 
> 2024-09-01 03:16:32     . logfile -> [stderr]@%INFO
> 2024-09-01 03:16:32     . maxinterval -> 5.00 seconds (5s)
> 2024-09-01 03:16:32 [2024-09-01 03:16:32,541: INFO/SpawnProcess-1] beat: Starting...
> 2024-09-01 03:16:34 Traceback (most recent call last):
> 2024-09-01 03:16:34   File "/usr/local/bin/watchfiles", line 8, in <module>
> 2024-09-01 03:16:34     sys.exit(cli())
> 2024-09-01 03:16:34              ^^^^^
> 2024-09-01 03:16:34   File "/usr/local/lib/python3.11/site-packages/watchfiles/cli.py", line 171, in cli
> 2024-09-01 03:16:34     run_process(
> 2024-09-01 03:16:34   File "/usr/local/lib/python3.11/site-packages/watchfiles/run.py", line 138, in run_process
> 2024-09-01 03:16:34     for changes in watch(
> 2024-09-01 03:16:34   File "/usr/local/lib/python3.11/site-packages/watchfiles/main.py", line 121, in watch
> 2024-09-01 03:16:34     raw_changes = watcher.watch(debounce, step, rust_timeout, stop_event)
> 2024-09-01 03:16:34                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```
> 
> The weird thing is, I tried running the same repo with Google IDX, and it worked fine

I have found the solution, hahaha! Just upgrade to [0.24.0](https://pypi.org/project/watchfiles/0.24.0/)

---

After some investigation, I realized that there is a [PR](https://github.com/animemoeus/backend/pull/351) in my repo that might be causing the error. I didn't notice this before because I was using Google IDX lately. Then, today I tried to switch back to my WSL setup and encountered the error.
