### ISSUE TITLE
PyPI distribution doesn't include sources for v0.16.0

### ISSUE THREAD

**Issue by davidbrochart** [samuelcolvin/watchfiles#175]
### Description

The source distribution is not included in PyPI for [v0.16.0](https://pypi.org/project/watchfiles/0.16.0/#files). It used to be in [v0.15.0](https://pypi.org/project/watchfiles/0.15.0/#files).
I think this is the cause of this conda-forge package [issue](https://github.com/conda-forge/watchfiles-feedstock/issues/8).

### Operating System & Architecture

N/A

### Python & Watchfiles Version

v0.16.0

**Comment by samuelcolvin** [comment]
Makes sense, weird it's not. Will fix tomorrow.

**Comment by samuelcolvin** [comment]
Explained by https://github.com/messense/maturin-action/issues/58.

Fix building now.

**Comment by davidbrochart** [comment]
I can see the [source distribution on PyPI](https://pypi.org/project/watchfiles/0.16.1/#files), but I get a 404 with:
```bash
wget https://pypi.io/packages/source/w/watchfiles/watchfiles-0.16.1.tar.gz
```
While this works fine:
```bash
wget https://pypi.io/packages/source/w/watchfiles/watchfiles-0.15.0.tar.gz
```
Any idea?

**Comment by samuelcolvin** [comment]
PyPI's cache being weird,

The following (link copied from https://pypi.org/project/watchfiles/0.16.1/#files) works fine

```
➤  curl -IL https://files.pythonhosted.org/packages/49/91/a9fbbe005ebb36fc17f78cf0dbe54ba71423375a7d6d6c75c01328fee6f0/watchfiles-0.16.1.tar.gz
HTTP/2 200 
last-modified: Mon, 25 Jul 2022 16:04:38 GMT
...
```

**Comment by davidbrochart** [comment]
But this is the [URL schema](https://github.com/conda-forge/watchfiles-feedstock/blob/3fe2dfa22ff4fe5ac8916bb17081bd504468dde4/recipe/meta.yaml#L10) for Python packages hosted on PyPI in conda-forge:
```
https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
```
With `name = watchfiles` and `version = 0.16.1`. It has always been like that and I don't think we can change it.

**Comment by davidbrochart** [comment]
@samuelcolvin your URL has a hash, but this seems to work:
```
https://files.pythonhosted.org/packages/source/w/watchfiles/watchfiles-0.16.1.tar.gz
```
Not sure if it's a general URL change in PyPI or a temporary issue.

**Comment by davidbrochart** [comment]
`https://pypi.io/packages/source/w/watchfiles/watchfiles-0.15.0.tar.gz` seems to work again, I'm updating the feedstock.

**Comment by samuelcolvin** [comment]
Thanks, my guess is you tried the URL before the file was ready and pypi or some part of it's CDN cached the 404, but hard to know.
