### ISSUE TITLE
Version 1?

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/watchfiles#186]
I think watchfiles is pretty stable and we should release version 1.

Unless anyone has any problems with that, or urgent bugs to fix/features to add; I'll release v1.0.0b1 in about a week.

**Comment by samuelcolvin** [comment]
Wait for:
* [ ] #187.

**Comment by pradyunsg** [comment]
> Unless anyone has any problems with that, or urgent bugs to fix/features to add; I'll release v1.0.0b1 in about a week.

Hi there @samuelcolvin! Would you consider making a non-[0ver](https://0ver.org/) release?

**Comment by samuelcolvin** [comment]
This is done, see #309.

Sorry for the delay @pradyunsg.
