### ISSUE TITLE
The watchfiles tarball released on PyPi do not include `Cargo.lock`

### ISSUE THREAD

**Issue by rszamszur** [samuelcolvin/watchfiles#192]
Hello there :wave:

Is there any particular reason why the `Cargo.lock` file is not included in the tarball released on PyPI? Having it would help build `watchfiles` with [Nix](https://nixos.org/). Otherwise, one has to hardcode and update cargo hashes, which can be a burden to maintain. I saw some projects include it (for instance: [cryptography-38.0.1.tar.gz](https://files.pythonhosted.org/packages/6d/0c/5e67831007ba6cd7e52c4095f053cf45c357739b0a7c46a45ddd50049019/cryptography-38.0.1.tar.gz) under `src/rust`). I do not know the playbook for Python-Rust projects, and I'm genuinely curious.

More context: https://github.com/nix-community/poetry2nix/issues/731

Have a good one!

**Comment by samuelcolvin** [comment]
Interesting, I would have thought it should be included, but I feel like there's a specific reason it's not.

See https://github.com/PyO3/maturin/discussions/1153, it seems that `cargo package --list --allow-dirty` does not include `Cargo.lock`, hence it's omitted.

Even if I add `Cargo.lock` to `Cargo.toml::package::include`, it still doesn't seem to be added to the tarball.

@messense what do you think?

**Comment by messense** [comment]
I guess cargo excludes `Cargo.lock` for library crate automatically. You can add it to sdist via `sdist-include` though

```toml
[tool.maturin]
sdist-include = ["Cargo.lock"]
```

**Comment by samuelcolvin** [comment]
Thanks @messense, what do you think about updating maturin to include it by default?
