### ISSUE TITLE
High CPU usage in version 0.16.1 watching python files

### ISSUE THREAD

**Issue by 4doom4** [samuelcolvin/watchfiles#195]
### Description

I am using watchfiles to monitor changes to python scripts loaded by celery in a docker (see below). While it works, I constantly have 75% CPU usage. Am I configuring something wrong? Is this a bug? I am not sure what you need to debug this.

### Example Code

```Python
watchfiles --filter python 'celery -A main worker --loglevel=info' &
```

### Operating System & Architecture

Linux-5.10.124-linuxkit-x86_64-with-glibc2.35
#1 SMP PREEMPT Thu Jun 30 08:18:26 UTC 2022

### Python & Watchfiles Version

python: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0], watchfiles: 0.16.1

**Comment by samuelcolvin** [comment]
Please enable debug mode and let me know if watchfiles is polling or using  os notifications.

The issue template questions were written for a reason, you haven't given me enough information to go on here.

**Comment by samuelcolvin** [comment]
I've formatted your comment so it's readable.

Looks pretty self explanatory - filesystem notifications are failing, so it's falling back to file polling and presumably your watching a lot of files.

Unless you're project really does have 10s if thousands of files, you're probably watching unnecessary directories.

Try restricting which files you watch.

**Comment by 4doom4** [comment]
Is there something I can do about the filesystem notifications failing? I don't really understand the details but is the file polling the cause of the high cpu usage? Would it be less if filesystem notifications would work? After limiting the number of files the CPU usage goes indeed down (as expected)

**Comment by 4doom4** [comment]
Thanks a lot for being so responsive!
