### ISSUE TITLE
"process already dead, exit code: 0"  echoed in console

### ISSUE THREAD

**Issue by petri** [samuelcolvin/watchfiles#205]
### Description

I'm running the "Example of run_process running a function" example from https://watchfiles.helpmanual.io/api/run_process/ 

The code appears to do what it is supposed to, but also, every time a change is detected,  a "process already dead, exit code: 0" message is echoed in the console.

Why does this happen, does it indicate a problem and is there any way to get rid of the message?

### Example Code

```Python
from watchfiles import run_process

def callback(changes):
    print('changes detected:', changes)

def foobar(a, b):
    print('foobar called with:', a, b)

if __name__ == '__main__':
    run_process('/static', target=foobar, args=(1, 2), callback=callback)
```

### Watchfiles Output

```Text
foobar called with: 1 2
changes detected: {(<Change.added: 1>, '/static/TTR')}
process already dead, exit code: 0
foobar called with: 1 2
changes detected: {(<Change.deleted: 3>, '/static/TTR'), (<Change.added: 1>, '/static/TTR')}
process already dead, exit code: 0
foobar called with: 1 2
^CKeyboardInterrupt caught, stopping watch
process already dead, exit code: 0
```

### Operating System & Architecture

MacOS 12.6.1 Python 3.10

### Python & Watchfiles Version

Python 3.10 , newest watchfiles from pypi

**Comment by samuelcolvin** [comment]
Well the process as finished.

This is expected.
