### ISSUE TITLE
Make set_version.py compatible with Cargo.lock

### ISSUE THREAD

**Issue by JuniorJPDJ** [samuelcolvin/watchfiles#213]
Hello! I'd like to use this script for packaging this library in Alpine Linux.
I'd like to run `maturin` with `--locked`, but setting version to other than locked one makes cargo fail.

Could you please extend regexp a bit so it also catches the name so we can call script twice (for `Cargo.toml` and `Cargo.lock`) and make use of `--locked`?

**Comment by messense** [comment]
You can run `cargo update -p watchfiles_rust_notify` after `set_version.py`, we do it this way on CI.

https://github.com/samuelcolvin/watchfiles/blob/305de4a44d63c198c25f2bc04ed7402da1197307/.github/workflows/ci.yml#L180-L186

**Comment by samuelcolvin** [comment]
I've got rid of the set-version thing in preparation for v1, see #309.
