### ISSUE TITLE
Poetry causes that WhachFiles fails in FastApi+Uvicorn scenario.

### ISSUE THREAD

**Issue by zvolsky** [samuelcolvin/watchfiles#219]
`uvicorn main:app --reload` want start.

This happens with virtual environment made from Poetry.
With virtual environment from `python -m venv` and `pip` it works well.

It happens already with "Hello world" example of FastApi, so I think the reported message "to many files open" is not correct.
Which is maybe the minimum thing wihich WatchFiles could improve here.
Of course more investigation would be great (if the rust watcher doesn't work well or if poetry makes something not correctly).

I don't repeat the description, it is [here](https://github.com/python-poetry/poetry/issues/7652) and [here](https://github.com/encode/uvicorn/issues/1030) (in the bottom comments).

**Comment by samuelcolvin** [comment]
Let start with one issue and create one here if we identify that this is a problem with watchfiles, not poetry.
