### ISSUE TITLE
Track file modifications

### ISSUE THREAD

**Issue by frank-lenormand** [samuelcolvin/watchfiles#227]
Hi,

This might be redundant with #201, sorry in advance if that’s the case.

I would like to be able to run the callback upon file modifications (i.e. the contents have changed). Currently, even `touch`-ing a file triggers the shell command.

**Comment by samuelcolvin** [comment]
best to implement in your own code by reading the file.

**Comment by frank-lenormand** [comment]
If that had top be handled by code that wraps `watchfiles`, I might as well implement all of #201 myself and not use `watchfiles` at all.

The idea is to have the tool react to events, one of which is “file has changed”.
