### ISSUE TITLE
Watchfiles not working without force_pulling 

### ISSUE THREAD

**Issue by amjltc295** [samuelcolvin/watchfiles#228]
### Description

Somehow the watchfiles package does not work in my Mac environment without setting force_pulling or `export WATCHFILES_FORCE_POLLING=true` in `.zshrc`. 

I'm using Mac M1. Ventura 13.1.
It works when I test it on a remote Ubuntu container.

### Example Code

```Python
from watchfiles import watch

# Not working
for changes in watch('./path/to/dir'):
    print(changes)

# Working
for changes in watch('./path/to/dir', force_polling=True):
    print(changes)
```

### Operating System & Architecture

macOS-10.16-x86_64-i386-64bit
Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000

### Python & Watchfiles Version

python: 3.9.12 (main, Apr  5 2022, 01:53:17) [Clang 12.0.0 ], watchfiles: 0.18.1

**Comment by samuelcolvin** [comment]
works fine on my mac, I'll need more details than this to investigate.
