### ISSUE TITLE
Watched file no longer watched after a change

### ISSUE THREAD

**Issue by sdondley** [samuelcolvin/watchfiles#235]
### Description

If I watch a single file and then make a change to it, the changs is picked up by watchlist. However, the second time a change is made to a file, watchfiles seems to no longer notice. watchfiles seems to work fine when watching a directory.

### Example Code

```Python
from watchfiles import run_process

def callback(changes):
    print('changes detected:', changes)

def foobar(a, b):
    print('foobar called with:', a, b)

if __name__ == '__main__':
    run_process('single_file', target=foobar, args=(1, 2), callback=callback)
```

### Watchfiles Output

```Text
./watch.py
foobar called with: 1 2
changes detected: {(<Change.deleted: 3>, '/home/admin/flask/single_file')}
process already dead, exit code: 0
foobar called with: 1 2

I get no more output as more changes are made to the file.
```

### Operating System & Architecture

Linux-6.1.0-10-cloud-amd64-x86_64-with-glibc2.36
#1 SMP PREEMPT_DYNAMIC Debian 6.1.37-1 (2023-07-03)

### Environment

using tmux

### Python & Watchfiles Version

python: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0], watchfiles: 0.19.0

**Comment by sdondley** [comment]
Just tested this on  my mac. Works perfectly and no problems with tmux. Hmm.

I should maybe also note that watchfiles was installed with pipx with things running in some kind of venv for python. I'm not familiar with how that works at all. It's the first I've come across this kind of thing.

**Comment by sdondley** [comment]
To try to find a workaround, I turned on force_polling:

```
#!/home/admin/.local/pipx/venvs/watchfiles/bin/python3
from watchfiles import watch

for changes in watch('testfile', force_polling=True):
    print(changes)
```

It seemed to work for a bit but then I got errors. Here's the output:

```
{(<Change.modified: 2>, 'testfile')}
{(<Change.modified: 2>, 'testfile')}
{(<Change.modified: 2>, 'testfile')}
{(<Change.modified: 2>, 'testfile')}
{(<Change.modified: 2>, 'testfile')}
Traceback (most recent call last):
  File "/home/admin/flask/./watch.py", line 4, in <module>
    for changes in watch('testfile', force_polling=True):
  File "/home/admin/.local/pipx/venvs/watchfiles/lib/python3.11/site-packages/watchfiles/main.py", line 105, in watch
    raw_changes = watcher.watch(debounce, step, rust_timeout, stop_event)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_rust_notify.WatchfilesRustInternalError: error in underlying watcher: No such file or directory (os error 2) about ["testfile"]
```

**Comment by sdondley** [comment]
Doing some more experimenting. Got a different error:

```
{(<Change.modified: 2>, 'testfile')}
thread 'notify-rs poll loop' panicked at 'internal error: entered unreachable code', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.0.0-pre.15/src/poll.rs:206:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/admin/test/./watch.py", line 4, in <module>
    for changes in watch('testfile', force_polling=True, raise_interrupt=False):
  File "/home/admin/.local/pipx/venvs/watchfiles/lib/python3.11/site-packages/watchfiles/main.py", line 105, in watch
    raw_changes = watcher.watch(debounce, step, rust_timeout, stop_event)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_rust_notify.WatchfilesRustInternalError: error in underlying watcher: No such file or directory (os error 2) about ["testfile"]
```
I'm making my edits to the file with vim.

**Comment by sdondley** [comment]
If I append to the file with a bash command like echo blah >> testfile, things works perfectly.

I suspect this has something to do with how vim modifies/updates files.

**Comment by sdondley** [comment]
Ok, after searching the issue queue on vim, I found this: https://github.com/samuelcolvin/watchfiles/issues/215

Which led me to this: https://github.com/notify-rs/notify/issues/394

So as best I can tell, this watchfiles isn't really going to work for me when watching a single file until some lower level issue in notify gets addressed.

**Comment by samuelcolvin** [comment]
If the file gets deleted, it's not surprising watching stops.

I would watch the entire directory with `rescursive=False`, then check which file changes in your own logic.

**Comment by sdondley** [comment]
What I ended up doing is putting the file in a subdir and symlinking to it from the parent dir and then watching the subdir.

**Comment by honglei** [comment]
When I use vi to edit and save the  watched file,  the lib give <Change.deleted: 3>, '/home/uos/conf/send.json', which caused watch stoped . But the file is not removed. 
Env: Python3.11.4/watchfiels 0.19/Debian10 arm64
