### ISSUE TITLE
PyPy 3.10 Wheels

### ISSUE THREAD

**Issue by olliemath** [samuelcolvin/watchfiles#239]
Hey, I'm wondering if you could add pypy3.10 wheels for watchfiles? Currently the following minimal dockerfile will fail:

```docker
FROM pypy:3.10-7.3.12-bullseye
RUN pip install watchfiles
```

Of course you can fix by installing the rust toolchain and compiling from source, but it would be nice to have wheels in pypi.

**Comment by samuelcolvin** [comment]
Can do, but waiting for https://github.com/PyO3/maturin-action/issues/166.

**Comment by samuelcolvin** [comment]
fixed in #248.

**Comment by olliemath** [comment]
Thanks!
