### ISSUE TITLE
Watchfiles does not report changes made by a different user in a directory

### ISSUE THREAD

**Issue by pallavg** [samuelcolvin/watchfiles#241]
I launch watchfiles to observe a directory path /a/b/c as userA. If userA adds/removes a file in /a/b/c, watchfiles can detect changes just fine. However, if userB puts a file in /a/b/c, watchfiles just ignores those. Is there some setting/mechanism thereby which, I can tell watchfiles to detect any changes irrespective of which user added/removed files? Thanks.

**Comment by samuelcolvin** [comment]
It would be helpful if you could include which OS you're using and any other details.

It might be fixed by setting `force_polling`.

**Comment by pallavg** [comment]
1. I'm using SUSE Enterprise LInux version 12.


2. I instantiate the watcher as follows. I am not doing anything special. 

```
 class MyFilter(DefaultFilter):
     allowed_extensions = '.txt', '.txt.gz'
     def __call__(self, change: Change, path: str) -> bool:
         return super().__call__(change, path) and path.endswith(self.allowed_extensions) and change == Change.added  

def _process(changes):
     """Process added  files."""

     for _, spofi_file in changes:
         log.info('Process %s', spofi_file)

def main()
    ....
    _incoming_dir = Path('/a/b/c').resolve()
    run_process(_incoming_dir, target=None, callback=_process, watch_filter=MyFilter(), step=30000)
```

**Comment by samuelcolvin** [comment]
Is it fixed by using force polling.

**Comment by pallavg** [comment]
Yes, it seems be working ok if I do 

os.environ['WATCHFILES_FORCE_POLLING'] = '1'

run_process(...)
