### ISSUE TITLE
Newly created subdirectories themselves arent getting watched recursively

### ISSUE THREAD

**Issue by nicholasbulka** [samuelcolvin/watchfiles#245]
### Description

Not sure if this is desired behavior or not but what I want to occur when a new subdirectory is created, is for files within that subdirectory to trigger a watch event. Right now it seems they are not. Say I watch parentDirectoryA and create childDirectoryB. I see the file event for a newly created directory trigger. But when I add a file to childDirectoryB the filewatcher does not seem to trigger. 

If this is actually the desired behavior, what is best practice for watching these additional subdirectories as they created?

### Operating System & Architecture

OS X Monterey 12.6

### Environment

Docker

### Python & Watchfiles Version

python:3.9.16 watchfiles: 0.19.0

**Comment by samuelcolvin** [comment]
I suspect this is a limitation of the underlying notify crate, let me know if you think there's something I can change here.

**Comment by samuelcolvin** [comment]
Have you tried force polling?

**Comment by samuelcolvin** [comment]
closing as no answer. The docs should explain how to stop the watcher and recreate.
