### ISSUE TITLE
.pyd ignored pattern is added back by PythonFilter.extensions

### ISSUE THREAD

**Issue by minusf** [samuelcolvin/watchfiles#255]
### Description

Not sure if oversight or by design:

```
...
    ignore_entity_patterns: Sequence[str] = (
        r'\.py[cod]$',
...
        self.extensions = ('.py', '.pyx', '.pyd') + tuple(extra_extensions)
```

### Watchfiles Output

```Text
.
```

### Operating System & Architecture

.

### Environment

.

### Python & Watchfiles Version

.

### Rust & Cargo Version

.

**Comment by samuelcolvin** [comment]
then use the default filter.
