### ISSUE TITLE
Problem installing on raspberry pi

### ISSUE THREAD

**Issue by gldrplt** [samuelcolvin/watchfiles#256]
### Description

I'm trying to install watchfiles globally on raspberry pi 4 running latest OS (Bookworm).
If I try to install using pip, the system says this environment is externally managed. It suggests to try:
apt install python3-watchfles.
This fails saying can't find module python3-watchfiles
I can install watchfiles in a virtual environment using pip, but I would prefer to install globally.
Any suggestions?

### Operating System & Architecture

raspberry pi 4 running Bookworm

### Python & Watchfiles Version

Python 3.11.2

**Comment by samuelcolvin** [comment]
No idea, perhaps an issue with how the distro packages it.

Why not just install globally with pip.

**Comment by gldrplt** [comment]
Here's the message I get when I try to install globally with pip

***@***.***:~ $ pip install watchfiles
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python
installation or OS distribution provider. You can override this, at the
risk of breaking your Python installation or OS, by passing
--break-system-packages.
hint: See PEP 668 for the detailed specification.
***@***.***:~ $

Google PEP 668 and you can see what they are trying to do to isolate Python
installations from the base OS.

**Comment by pootle** [comment]
ditto. I understand that PEP 558 is a good idea on larger systems, but on small dedicated single function boxes this is a PITA as --break-system -packages itself does not work

**Comment by DarylStark** [comment]
Is the following command working?

```
pip install --user watchfiles
```

This will install it into your user profile. Still not a virtual env, but also not as global as the `sudo pip install`.

**Comment by pootle** [comment]
Yup that's the sort of answer I'm after, thanks

**Comment by samuelcolvin** [comment]
Great, closing this.
