### ISSUE TITLE
Please make a new release using pyo3 0.20.3

### ISSUE THREAD

**Issue by mgorny** [samuelcolvin/watchfiles#261]
### Description

The current PyO3 version of 0.20.0 is broken on PowerPC (https://github.com/PyO3/pyo3/commit/9d1b11f70459367593e4cb92919f5f98c156dda9). This is preventing PowerPC users from installing watchfiles cleanly.

Could you update PyO3 and make a new release, please?

### Operating System & Architecture

Linux-6.1.60-gentoo-dist-hardened-ppc-POWER9_-architected-,_altivec_supported-with-glibc2.38
#1 SMP Fri Dec  1 22:10:49 UTC 2023

### Python & Watchfiles Version

n/a (not installable)

### Rust & Cargo Version

cargo 1.74.1 (ecb9851af 2023-10-18); rustc 1.74.1 (a28077b28 2023-12-04)

**Comment by gaby** [comment]
@mgorny Isn't this fixed by https://github.com/samuelcolvin/watchfiles/releases/tag/v0.21.0 ?

**Comment by mgorny** [comment]
Nope. `Cargo.lock` says 0.20.0.

**Comment by gaby** [comment]
@samuelcolvin Any chance to get a new release with update dependencies. PyO3 is already on v0.21.x

**Comment by samuelcolvin** [comment]
PR welcome, otherwise I'll try soon.

**Comment by gaby** [comment]
I was going to update them, then realize PyO3 v0.21.x changed the API and I dont know Rust 😂

I cam submit one for dependabot config

**Comment by samuelcolvin** [comment]
All updates are complete, watchfiles now uses latest pyo3, and i've updated actions version.

@gaby and @mgorny please try the latest version from `main` and confirm you're happy, then I'll do a release.

**Comment by mgorny** [comment]
Yeah, I can confirm `main` now builds on PowerPC and has no PPC-specific test regressions. However, it is still affected by #254. But I'm happy to just skip that test, if need be.

**Comment by samuelcolvin** [comment]
[v0.22.0](https://github.com/samuelcolvin/watchfiles/releases/tag/v0.22.0) is released.

**Comment by gaby** [comment]
@samuelcolvin Thank you!
