### ISSUE TITLE
Release wheels for Python 3.13

### ISSUE THREAD

**Issue by hugovk** [samuelcolvin/watchfiles#276]
The [Python 3.13 beta is out](https://discuss.python.org/t/python-3-13-0b1-now-available/52891) and the release manager has a call to action:

> We **strongly encourage** maintainers of third-party Python projects to **test with 3.13** during the beta phase and report issues found to [the Python bug tracker ](https://github.com/python/cpython/issues) as soon as possible. While the release is planned to be feature complete entering the beta phase, it is possible that features may be modified or, in rare cases, deleted up until the start of the release candidate phase (Tuesday 2024-07-30). Our goal is to have no ABI changes after beta 4 and as few code changes as possible after 3.13.0rc1, the first release candidate. To achieve that, it will be **extremely important** to get as much exposure for 3.13 as possible during the beta phase.

To help test projects which use watchfiles, it would be very helpful to release wheels to PyPI for those of us who don't have the Rust toolchain set up. Currently we get:

```pytb
❯ python3.13 -m pip install watchfiles
Collecting watchfiles
  Using cached watchfiles-0.21.0.tar.gz (37 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

      Checking for Rust toolchain....
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Thank you!

**Comment by EwoutH** [comment]
Currently my Python 3.13 [CI build](https://github.com/projectmesa/mesa/pull/2173) is stuck on `watchfiles`, with [this error](https://github.com/projectmesa/mesa/actions/runs/9841104071/job/27167227191).

One thing that needs to be done is to update [PyO3](https://github.com/PyO3/pyo3) to [0.22.0](https://github.com/PyO3/pyo3/releases/tag/v0.22.0) or [higher](https://github.com/PyO3/pyo3/releases/latest), since those support Python 3.13. There is a migration guide available here: https://pyo3.rs/v0.22.1/migration

In https://github.com/crate-py/rpds/pull/79 a similar upgrade was done, it might be useful as reference.

Unfortunately, I'm not a Rust dev, so not able to do it myself.

**Comment by samuelcolvin** [comment]
[v0.23.0](https://pypi.org/project/watchfiles/0.23.0/) is released with support for 3.13.

**Comment by Piyushj007** [comment]
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

run this command in git bash

**Comment by lordfeck** [comment]
I'm getting this error when I attempt to install Watchfiles on Mac OS Sequoia 15 (Apple Silicon). I'd prefer not to install rust just for one dependency. Are the binaries available on pip for my system's architecture?

**Comment by samuelcolvin** [comment]
There are wheels for 3.13 on macos - https://pypi.org/project/watchfiles/#files

If you're having an issue, please create a new issue with as much detail as possible.
