### ISSUE TITLE
Ability to exclude certain directories from being watched

### ISSUE THREAD

**Issue by powellnorma** [samuelcolvin/watchfiles#288]
I know there is watch_filter - But is it possible to exclude some directories (that perhaps contain many small files I don't care about) from being monitored in the first place?

I guess one way would be to use `recursive=False`, and then list all subdirectories I am interested in. But what if in one of those a new directory gets created - Will that new directory be monitored? I guess no, since `recursive=False`?

**Comment by samuelcolvin** [comment]
No plans to add specific support to this since it's not supported by the underlying watch implementations.

You'll need to support this "manually" using the current API.
