### ISSUE TITLE
Doc link is broken

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [samuelcolvin/watchfiles#289]
### Description

[watchfiles.helpmanual.io](https://watchfiles.helpmanual.io/) not working

### Operating System & Architecture

n/a

### Python & Watchfiles Version

July 11, 2024

**Comment by samuelcolvin** [comment]
It's working fine for me.

Please can you give more details than "not working".

**Comment by Andrew-Chen-Wang** [comment]
<img width="795" alt="Screenshot 2024-07-11 at 13 50 45" src="https://github.com/samuelcolvin/watchfiles/assets/60190294/fb24eb6c-7a8c-41e7-a041-9de27782ee69">

Hi sorry for being unclear

**Comment by Andrew-Chen-Wang** [comment]
I believe it might be because of a corporate firewall; apologies!
